### ISSUE TITLE
Which version of Period04 is used in this script?

### ISSUE THREAD

**Issue by Vouq** [keatonb/pyperiod04#1]
I tried this script but it doesn't work well for my Period04 v1.2.0. According to the help file of Period04, there is no 'savefourier' function. Is there a newer version to support this function?

**Comment by keatonb** [comment]
I'm afraid that I haven't used this code in a long time and I no longer have it working with Period04.  I think there was a newer version floating around with additional command line functionality that this worked with, but as far and I know it was never officially released.

Incidentally, I have been working on developing an all-Python code to reproduce the basic Period04 functionality, so keep an eye open for me to release that, hopefully within the next couple of months.
